apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aman-tg
  namespace: aman
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "15m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - aman.kooleklabs.com
    secretName: aman-cf-origin-tls
  rules:
  - host: aman.kooleklabs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aman-api-svc
            port:
              number: 3000
